shinyUI(
  fluidPage(theme = "bootstrap.min.css",
    fluidRow(
      column(leftWidth,
	br(),
	br(),
	br(),
	selectInput("firstShow",
		    "Pick a show",
		    choices = showsTitles,
		    selected = showsTitles[1]),
        conditionalPanel("input.typeRating != 'vs'",
	  checkboxGroupInput("firstSeasons",
			     "Seasons",
			     choices = defaultSeasonsChoices,
			     selected = defaultSeasonsChoices,
			     inline = TRUE)),
	conditionalPanel("input.typeRating == 'vs'",
	  radioButtons("firstSeasonsRadio",
		       "Seasons",
		       choices = defaultSeasonsChoices,
		       inline = TRUE)),
	conditionalPanel("input.tabPanels == 'compareShows'",
	  selectInput("secondShow",
		      "Compare it with",
		      choices = showsTitles,
		      selected = showsTitles[2]),
          conditionalPanel("input.typeRating != 'vs'",
	    checkboxGroupInput("secondSeasons",
			       "Seasons",
			       choices = defaultSeasonsChoicesTwo,
			       selected = defaultSeasonsChoicesTwo,
			       inline = TRUE)),
	  conditionalPanel("input.typeRating == 'vs'",
	    radioButtons("secondSeasonsRadio",
			 "Seasons",
			 choices = defaultSeasonsChoicesTwo,
			 inlin = T))),
	useShinyjs(),
        radioButtons("typeRating",
		   "Type of ratings",
		   choices = c("IMDb ratings" = "imdbRating",
			       "Viewership" = "nielsenRating",
			       "IMDb vs viewership" = "vs"),
		   selected = "imdbRating"),
	checkboxInput("trend",
		      "Add trend line",
		      value = FALSE),
	checkboxInput("background",
		      "Display other show's ratings in the background",
		      value = TRUE),
	checkboxInput("separate",
		      "Place seasons on separate panels",
		      value = FALSE),
        sliderInput("rt",
                    "Rating",
                    min = floor(defaultSliderLeft),
		    max = ceiling(defaultSliderRight),
                    value = c(defaultSliderLeft,
			      defaultSliderRight),
		    step = 0.1),
        dateRangeInput("dates",
                  "Episodes aired between",
		  min = defaultMinDate,
		  max = defaultMaxDate,
		  start = defaultMinDate,
		  end = defaultMaxDate)),
      column(rightWidth,
        navbarPage("Comicbook TV",
          tabPanel("One show",
		   value = "oneShow",
            plotOutput("oneShowPlot",
		       click = "plotOneClick"),
	    htmlOutput("oneShowInfo")),           
          tabPanel("Compare shows",
		   value = "compareShows",
	    plotOutput("compareShowsPlot",
		       click = "plotTwoClick"),
	    textOutput("compareTop"),
	    textOutput("compareMid"),
	    htmlOutput("compareBot")),
          tabPanel("All shows",
		   value = "compareShows",
	    plotOutput("allShowsPlot")),
          tabPanel("About this app",
		   value = "aboutThisApp",
            includeMarkdown("www/about.md")),
          id = "tabPanels"))
)))
