shinyUI(
  fluidPage(
    fluidRow(
      column(leftWidth,
	br(),
	br(),
	br(),
	selectInput("firstShow",
		    "Select show to display",
		    choices = showsTitles,
		    selected = showsTitles[1]),
	checkboxGroupInput("firstSeasons",
		           "Seasons",
			   choices = defaultSeasonsChoices,
			   selected = defaultSeasonsChoices,
			   inline = TRUE),
	conditionalPanel("input.tabPanels == 'compareShows'",
	  selectInput("secondShow",
		      "Select show to compare",
		      choices = showsTitles,
		      selected = showsTitles[2]),
	checkboxGroupInput("secondSeasons",
		           "Seasons",
			   choices = defaultSeasonsChoicesTwo,
			   selected = defaultSeasonsChoicesTwo,
			   inline = TRUE)),
        radioButtons("typeRating",
		   "",
		   choices = c("IMDb ratings" = "imdbRating",
			       "Viewership" = "nielsenRating"),
		   selected = "imdbRating"),
	checkboxInput("trend",
		      "Display trend line",
		      value = FALSE),
        sliderInput("rt",
                    "Rating",
                    min = floor(defaultSliderLeft),
		    max = ceiling(defaultSliderRight),
                    value = c(defaultSliderLeft,
			      defaultSliderRight),
		    step = 0.1),
        dateRangeInput("dates",
                  "Display episode aired between",
		  min = defaultMinDate,
		  max = defaultMaxDate,
		  start = defaultMinDate,
		  end = defaultMaxDate)),
      column(rightWidth,
        navbarPage("Comicbook TV",
          tabPanel("One show",
		   value = "oneShow",
            plotOutput("oneShowPlot",
		       click = "plotOneClick"),
	    htmlOutput("oneShowInfo")),           
          tabPanel("Compare shows",
		   value = "compareShows",
	    plotOutput("compareShowsPlot",
		       click = "plotTwoClick"),
	    textOutput("compareTop"),
	    textOutput("compareMid"),
	    htmlOutput("compareBot")),
          tabPanel("All shows",
		   value = "compareShows",
	    plotOutput("allShowsPlot")),
          tabPanel("About this app",
		   value = "aboutThisApp",
            includeMarkdown("www/about.md")),
          id = "tabPanels"))
)))
